import { memo } from 'react'
import { fmt } from '../../lib/format'
import type { Baseline } from '../../hooks/useSimulationEngine'
import type { DerivedMetrics, ReactorConfig } from '../../simulation/types'

interface InsightsPanelProps {
  metrics: DerivedMetrics | null
  interpretation: string[]
  config: ReactorConfig | null
  runLabel: string
  baseline: Baseline | null
  onSetBaseline: () => void
  onClearBaseline: () => void
  onExportCsv: () => void
  onExportJson: () => void
  onExportImage: () => void
  exportError: string | null
  large?: boolean
}

interface Row {
  label: string
  unit: string
  get: (m: DerivedMetrics) => number
  digits: number
}

const ROWS: Row[] = [
  { label: 'Final biomass', unit: 'g/L', get: (m) => m.finalBiomass, digits: 3 },
  { label: 'Peak biomass', unit: 'g/L', get: (m) => m.maxBiomass, digits: 3 },
  { label: 'Final substrate', unit: 'g/L', get: (m) => m.finalSubstrate, digits: 3 },
  { label: 'Final product', unit: 'g/L', get: (m) => m.finalProduct, digits: 3 },
  { label: 'Peak growth rate', unit: 'h⁻¹', get: (m) => m.maxGrowthRate, digits: 3 },
  { label: 'Mean productivity', unit: 'g/h', get: (m) => m.productivity, digits: 3 },
  { label: 'Realized yield', unit: 'g/g', get: (m) => m.realizedYield, digits: 3 },
  { label: 'Final volume', unit: 'L', get: (m) => m.finalVolume, digits: 2 },
]

function delta(a: number, b: number): string {
  if (!Number.isFinite(a) || !Number.isFinite(b)) return '—'
  if (Math.abs(a) < 1e-9) return Math.abs(b) < 1e-9 ? '0%' : 'new'
  const pct = ((b - a) / Math.abs(a)) * 100
  return `${pct > 0 ? '+' : ''}${pct.toFixed(0)}%`
}

function InsightsPanel({
  metrics,
  interpretation,
  config,
  runLabel,
  baseline,
  onSetBaseline,
  onClearBaseline,
  onExportCsv,
  onExportJson,
  onExportImage,
  exportError,
  large = false,
}: InsightsPanelProps) {
  if (!metrics || !config) {
    return (
      <section className="glass p-5 text-sm text-muted" aria-label="Results and insights">
        <h3 className="mb-1 font-display text-sm font-semibold text-paper">What happened?</h3>
        Run an experiment to get final metrics and a plain-language explanation of the trajectory, generated by fixed rules from the simulation data (no external AI).
      </section>
    )
  }

  return (
    <section className="flex flex-col gap-4" aria-label="Results and insights">
      <div className="glass p-5">
        <h3 className={`mb-3 font-display font-semibold text-paper ${large ? 'text-xl' : 'text-sm'}`}>What happened?</h3>
        <ul className={`flex flex-col gap-2.5 leading-relaxed text-paper/90 ${large ? 'text-lg' : 'text-[13px]'}`}>
          {interpretation.map((s, i) => (
            <li key={i} className="flex gap-2.5">
              <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-aqua" aria-hidden="true" />
              <span>{s}</span>
            </li>
          ))}
        </ul>
        {config.reactorType === 'cstr' && (
          <p className="mt-3 rounded border border-ink-500 px-3 py-2 font-mono text-xs text-muted">
            Outcome: <span className={metrics.washedOut ? 'text-readout-product' : 'text-aqua'}>{metrics.washedOut ? 'washed out' : 'stable culture'}</span>
          </p>
        )}
      </div>

      <div className="glass p-5">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
          <h3 className="font-display text-sm font-semibold text-paper">{baseline ? 'Comparison' : 'Final metrics'}</h3>
          <div className="flex flex-wrap gap-2">
            {!baseline ? (
              <button type="button" onClick={onSetBaseline} className="btn-ghost btn-sm">
                Save as comparison baseline
              </button>
            ) : (
              <button type="button" onClick={onClearBaseline} className="btn-ghost btn-sm hover:!border-readout-product hover:!text-readout-product">
                Clear baseline
              </button>
            )}
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[380px] text-left font-mono text-xs">
            <thead>
              <tr className="border-b border-ink-600 text-muted">
                <th className="py-1.5 pr-2 font-normal">Metric</th>
                {baseline && <th className="px-2 py-1.5 text-right font-normal">{baseline.label}</th>}
                <th className="px-2 py-1.5 text-right font-normal">{baseline ? runLabel : 'Value'}</th>
                {baseline && <th className="py-1.5 pl-2 text-right font-normal">Δ</th>}
              </tr>
            </thead>
            <tbody>
              {ROWS.map((r) => {
                const cur = r.get(metrics)
                const base = baseline ? r.get(baseline.metrics) : null
                return (
                  <tr key={r.label} className="border-b border-ink-700/70">
                    <th scope="row" className="py-1.5 pr-2 font-normal text-paper/85">
                      {r.label} <span className="text-dim">{r.unit}</span>
                    </th>
                    {baseline && <td className="px-2 py-1.5 text-right text-muted">{fmt(base, r.digits)}</td>}
                    <td className="px-2 py-1.5 text-right text-paper">{fmt(cur, r.digits)}</td>
                    {baseline && base !== null && <td className="py-1.5 pl-2 text-right text-aqua">{delta(base, cur)}</td>}
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
        {baseline && (
          <p className="mt-2 text-[11px] text-dim">
            The baseline stays saved while you change experiments or reactor modes, so any two runs can be compared.
          </p>
        )}
      </div>

      <div className="glass p-5">
        <h3 className="mb-3 font-display text-sm font-semibold text-paper">Export</h3>
        <div className="flex flex-wrap gap-2">
          <button type="button" onClick={onExportCsv} className="btn-ghost btn-sm">
            Trajectory CSV
          </button>
          <button type="button" onClick={onExportJson} className="btn-ghost btn-sm">
            Full experiment JSON
          </button>
          <button type="button" onClick={onExportImage} className="btn-ghost btn-sm">
            Reactor image (PNG)
          </button>
        </div>
        <p className="mt-2 text-[11px] text-dim">
          Chart images are downloadable with the PNG button on each chart. Filenames include the experiment, duration and timestamp.
        </p>
        {exportError && (
          <p role="alert" className="mt-2 text-xs text-readout-product">
            {exportError}
          </p>
        )}
      </div>
    </section>
  )
}

export default memo(InsightsPanel)
