import { memo } from 'react'
import { fmt } from '../../lib/format'
import type { Baseline } from '../../hooks/useSimulationEngine'
import type { DerivedMetrics, ReactorConfig } from '../../simulation/types'

interface InsightsPanelProps {
  metrics: DerivedMetrics | null
  interpretation: string[]
  config: ReactorConfig | null
  runLabel: string
  baseline: Baseline | null
  large?: boolean
}

interface Row {
  label: string
  unit: string
  get: (m: DerivedMetrics) => number
  digits: number
}

const ROWS: Row[] = [
  { label: 'Final biomass', unit: 'g/L', get: (m) => m.finalBiomass, digits: 3 },
  { label: 'Peak biomass', unit: 'g/L', get: (m) => m.maxBiomass, digits: 3 },
  { label: 'Final substrate', unit: 'g/L', get: (m) => m.finalSubstrate, digits: 3 },
  { label: 'Final product', unit: 'g/L', get: (m) => m.finalProduct, digits: 3 },
  { label: 'Peak growth rate', unit: 'h⁻¹', get: (m) => m.maxGrowthRate, digits: 3 },
  { label: 'Mean productivity', unit: 'g/h', get: (m) => m.productivity, digits: 3 },
  { label: 'Realised yield', unit: 'g/g', get: (m) => m.realizedYield, digits: 3 },
  { label: 'Final volume', unit: 'L', get: (m) => m.finalVolume, digits: 2 },
]

function delta(a: number, b: number): { text: string; sign: number } {
  if (!Number.isFinite(a) || !Number.isFinite(b)) return { text: '—', sign: 0 }
  if (Math.abs(a) < 1e-9) return Math.abs(b) < 1e-9 ? { text: '0%', sign: 0 } : { text: 'new', sign: 1 }
  const pct = ((b - a) / Math.abs(a)) * 100
  if (Math.abs(pct) < 0.5) return { text: '0%', sign: 0 }
  return { text: `${pct > 0 ? '+' : '−'}${Math.abs(pct).toFixed(0)}%`, sign: Math.sign(pct) }
}

/** Plain-language reading of the run, and the end-of-run figures of merit. */
function InsightsPanel({ metrics, interpretation, config, runLabel, baseline, large = false }: InsightsPanelProps) {
  if (!metrics || !config) {
    return (
      <p className="text-ui text-ink-3" role="status">
        Results appear after a run: a reading of the trajectory generated by fixed rules from the simulated data, and the final figures of merit.
      </p>
    )
  }

  return (
    <div className="grid gap-x-12 gap-y-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]">
      <section aria-labelledby="reading-h">
        <h3 id="reading-h" className="t-sub mb-3">
          Reading of the run
        </h3>
        {config.reactorType === 'cstr' && (
          <p className={`mb-4 inline-flex items-center gap-2 rounded-md px-2.5 py-1 text-label font-medium ${metrics.washedOut ? 'bg-danger-soft text-danger' : 'bg-ok-soft text-ok'}`}>
            <span className={`h-1.5 w-1.5 rounded-full ${metrics.washedOut ? 'bg-danger' : 'bg-ok'}`} aria-hidden="true" />
            {metrics.washedOut ? 'Outcome: culture washed out' : 'Outcome: stable culture'}
          </p>
        )}
        <ul className={`flex flex-col gap-3 ${large ? 'text-lg' : 'text-body'} leading-relaxed text-ink-2`}>
          {interpretation.map((s, i) => (
            <li key={i} className="grid grid-cols-[1.25rem_1fr]">
              <span className="mt-[12px] h-px w-2.5 bg-ink-3" aria-hidden="true" />
              <span>{s}</span>
            </li>
          ))}
        </ul>
        <p className="mt-4 text-label text-ink-3">Generated by fixed rules from the simulated trajectory.</p>
      </section>

      <section aria-labelledby="metrics-h">
        <h3 id="metrics-h" className="t-sub mb-3">
          {baseline ? 'Comparison with baseline' : 'Figures of merit'}
        </h3>
        <div className="overflow-x-auto">
          <table className="data-table min-w-[360px]">
            <thead>
              <tr>
                <th scope="col">Quantity</th>
                {baseline && (
                  <th scope="col" className="text-right">
                    <span className="inline-flex items-center gap-1.5">
                      <span className="swatch swatch-dashed text-ink-3" aria-hidden="true" />
                      <span className="max-w-[9rem] truncate">{baseline.label}</span>
                    </span>
                  </th>
                )}
                <th scope="col" className="text-right">
                  {baseline ? (
                    <span className="inline-flex items-center gap-1.5">
                      <span className="swatch text-ink" aria-hidden="true" />
                      <span className="max-w-[9rem] truncate">{runLabel}</span>
                    </span>
                  ) : (
                    'Value'
                  )}
                </th>
                {baseline && (
                  <th scope="col" className="!pr-0 text-right">
                    Change
                  </th>
                )}
              </tr>
            </thead>
            <tbody>
              {ROWS.map((r) => {
                const cur = r.get(metrics)
                const base = baseline ? r.get(baseline.metrics) : null
                const d = base !== null ? delta(base, cur) : null
                return (
                  <tr key={r.label}>
                    <th scope="row" className="!border-b !border-line py-2.5 pr-4 text-left font-normal text-ink-2">
                      {r.label} <span className="font-mono text-micro text-ink-3">{r.unit}</span>
                    </th>
                    {baseline && <td className="num text-right font-mono text-ink-3">{fmt(base, r.digits)}</td>}
                    <td className="num text-right font-mono text-ink">{fmt(cur, r.digits)}</td>
                    {d && <td className={`num !pr-0 text-right font-mono ${d.sign === 0 ? 'text-ink-3' : 'text-ink'}`}>{d.text}</td>}
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
        {baseline && <p className="mt-3 text-label text-ink-3">The baseline stays saved while you change experiments or reactor modes. It is drawn dashed on the figures.</p>}
      </section>
    </div>
  )
}

export default memo(InsightsPanel)
